const WHATSAPP_NUMBER="212624221246";
// Collez ici l'URL du déploiement Google Apps Script après la configuration (voir SETUP-GOOGLE-SHEETS.md).
const ORDER_API_URL="https://script.google.com/macros/s/AKfycbwymlzcjdzcjy2zutSqXsW1XuV_GHwlUZN3ApGgudpIegHLJfr8O1n9HP3onQ6WRg/exec";
// Ajoutez ici vos 200+ parfums : [nom, genre, famille]. La recherche s'adapte automatiquement.
const PERFUMES=[["Ambre Solaire","Femme","Ambré"],["Musc Blanc","Mixte","Musqué"],["Oud Royal","Homme","Boisé"],["Fleur de Jasmin","Femme","Floral"],["Vanille Dorée","Femme","Gourmand"],["Rose d'Orient","Femme","Floral"],["Bois de Santal","Homme","Boisé"],["Neroli Intense","Mixte","Hespéridé"],["Santal Élixir","Homme","Boisé"],["Velours Noir","Mixte","Oriental"],["Iris Précieux","Femme","Poudré"],["Cuir de Minuit","Homme","Cuiré"],["Figue Blanche","Mixte","Fruité"],["Oud Safran","Homme","Épicé"],["Pivoine d'Or","Femme","Floral"],["Musc Cashmere","Mixte","Musqué"],["Cèdre Absolu","Homme","Boisé"],["Fleur de Coton","Femme","Poudré"],["Éclat d'Agrumes","Mixte","Hespéridé"],["Prune Ambrée","Femme","Gourmand"]].map(([name,gender,family])=>({name,gender,family}));
let selectedOffer={},chosen=[null,null,null,null],activeSlot=0,filter='Tous';const modal=document.querySelector('#order-modal'),box=document.querySelector('#perfume-options'),count=document.querySelector('#selection-count');
function renderPicker(){const q=(document.querySelector('#catalog-search')?.value||'').toLocaleLowerCase('fr'),matches=PERFUMES.filter(p=>(filter==='Tous'||p.gender===filter)&&`${p.name} ${p.gender} ${p.family}`.toLocaleLowerCase('fr').includes(q)).slice(0,30);box.innerHTML=`<div class="chosen-slots">${chosen.map((p,i)=>`<button type="button" class="slot ${activeSlot===i?'active':''} ${p?'filled':''}" data-slot="${i}"><small>PARFUM ${i+1}</small><b>${p?p.name:'Choisir un parfum'}</b><span>${p?`${p.gender} · ${p.family}`:'Cliquez pour rechercher'}</span>${p?'<i aria-label="Retirer">×</i>':''}</button>`).join('')}</div><div class="catalog-search"><span>⌕</span><input id="catalog-search" autocomplete="off" placeholder="Rechercher un parfum, une famille…" value="${q}"></div><div class="filters">${['Tous','Femme','Homme','Mixte'].map(x=>`<button type="button" data-filter="${x}" class="${filter===x?'selected':''}">${x}</button>`).join('')}</div><div class="result-label">${matches.length} parfum${matches.length>1?'s':''} affiché${matches.length>1?'s':''} <span>pour l'emplacement ${activeSlot+1}</span></div><div class="search-results">${matches.map(p=>`<button type="button" class="result ${chosen.some(x=>x?.name===p.name)?'already':''}" data-name="${p.name}"><b>${p.name}</b><span>${p.gender} · ${p.family}</span><i>${chosen.some(x=>x?.name===p.name)?'Déjà choisi':'Ajouter +'}</i></button>`).join('')||'<p class="empty">Aucun parfum trouvé.</p>'}</div>`}
function refresh(){const n=chosen.filter(Boolean).length;count.textContent=`${n} / 4 parfums sélectionnés`;count.classList.toggle('ready',n===4)}
box.addEventListener('click',e=>{const s=e.target.closest('.slot'),remove=e.target.closest('.slot i'),r=e.target.closest('.result'),f=e.target.closest('[data-filter]');if(remove){activeSlot=+remove.closest('.slot').dataset.slot;chosen[activeSlot]=null;renderPicker();refresh();return}if(s){activeSlot=+s.dataset.slot;renderPicker();return}if(f){filter=f.dataset.filter;renderPicker();return}if(r&&!r.classList.contains('already')){chosen[activeSlot]=PERFUMES.find(x=>x.name===r.dataset.name);activeSlot=chosen.findIndex(x=>!x);if(activeSlot<0)activeSlot=0;renderPicker();refresh()}});box.addEventListener('input',e=>{if(e.target.id==='catalog-search'){renderPicker();const input=document.querySelector('#catalog-search');input.focus();input.setSelectionRange(input.value.length,input.value.length)}});
document.querySelectorAll('.select-offer').forEach(btn=>btn.addEventListener('click',()=>{selectedOffer=btn.dataset;document.querySelector('#offer-name').textContent=selectedOffer.size;document.querySelector('#order-form').reset();chosen=[null,null,null,null];activeSlot=0;filter='Tous';renderPicker();refresh();modal.classList.add('visible');document.body.style.overflow='hidden'}));function close(){modal.classList.remove('visible');document.body.style.overflow=''}document.querySelector('.close').addEventListener('click',close);modal.addEventListener('click',e=>{if(e.target===modal)close()});
document.querySelector('#order-form').addEventListener('submit',async e=>{e.preventDefault();if(chosen.some(x=>!x)){count.textContent='Veuillez compléter vos 4 parfums.';count.classList.remove('ready');return}if(!ORDER_API_URL){count.textContent='La réception automatique est en cours de configuration.';count.classList.remove('ready');return}const d=new FormData(e.target),order={coffret:selectedOffer.size,prix:selectedOffer.price,parfums:chosen.map(x=>x.name),nom:d.get('name'),telephone:d.get('phone'),ville:d.get('city'),adresse:d.get('address')},button=e.target.querySelector('.submit');button.disabled=true;button.innerHTML='Enregistrement en cours…';try{await fetch(ORDER_API_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(order)});document.querySelector('#form-view').hidden=true;document.querySelector('#success-view').hidden=false}catch(error){count.textContent='Une erreur est survenue. Veuillez réessayer.';count.classList.remove('ready')}finally{button.disabled=false;button.innerHTML='Enregistrer ma commande <span>✓</span>'}});
